version = 1

[[annotations]]
path = "include/catch/catch.hpp"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) 2022 Two Blue Cubes Ltd. All rights reserved."
SPDX-License-Identifier = "BSL-1.0"
