/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "6.2.6"

#define QTUITOOLS_VERSION 0x060206

#endif // QT_QTUITOOLS_VERSION_H
