/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "6.2.12"

#define QTUITOOLS_VERSION 0x06020C

#endif // QT_QTUITOOLS_VERSION_H
