/* This file was generated by syncqt. */
#ifndef QT_QTUIPLUGIN_VERSION_H
#define QT_QTUIPLUGIN_VERSION_H

#define QTUIPLUGIN_VERSION_STR "6.2.10"

#define QTUIPLUGIN_VERSION 0x06020A

#endif // QT_QTUIPLUGIN_VERSION_H
