/* This file was generated by syncqt. */
#ifndef QT_QTTOOLS_VERSION_H
#define QT_QTTOOLS_VERSION_H

#define QTTOOLS_VERSION_STR "6.2.11"

#define QTTOOLS_VERSION 0x06020B

#endif // QT_QTTOOLS_VERSION_H
